const SPAM_MSGS = {
  CZ: [
    "{0} si pálí prst o displej!",
    "Pozor, {0} to tam sází jako o život!",
    "Velitel {0} má asi křeč v prstu!",
    "{0} žhaví obrazovku na maximum!",
    "Zastavte někdo hráče {0}, nebo nám praskne sklo!"
  ],
  EN: [
    "{0} is burning their finger on the screen!",
    "Watch out, {0} is tapping like crazy!",
    "Commander {0} must have a finger cramp!",
    "{0} is heating up the display to the max!",
    "Someone stop {0} before the glass breaks!"
  ]
};

const JOKES = {
  CZ: [
    "„Kouříš?“ – „Jen po sexu.“ – „Takže vůbec.“",
    "Jsem naprosto spolehlivý! To jen okolnosti jsou proti mně!",
    "To není katastrofa, to je totální smeg!",
    "Rimmere, ty jsi takový trouba, že bys ztratil i vlastní stín.",
    "Krytone, přestaň být tak zatraceně poslušný!",
    "Jsem poslední člověk naživu… a jsem to zrovna já.",
    "Tohle je plán? To je spíš zoufalý pokus neumřít.",
    "Když se něco může pokazit, Rimmer to pokazí.",
    "Tohle je nejhorší situace, v jaké jsem kdy byl… a to jsem byl Rimmerův spolubydlící.",
    "Já nejsem zbabělec! Jen mám vysoce vyvinutý pud sebezáchovy.",
    "Kocoure, ty jsi úplně k ničemu. – Ale vypadám u toho skvěle.",
    "To není problém. To je naprostá katastrofa.",
    "Rimmere, ty jsi chodící důkaz, že evoluce může jít i pozpátku.",
    "Já mám plán. A je dokonce lepší než žádný plán.",
    "Jsme ztraceni ve vesmíru, bez šance na návrat… dá si někdo curry?",
    "Já jsem tak skvělý, až je to skoro nespravedlivé.",
    "Rimmere, ty jsi úplně k ničemu… a ještě k tomu pomalý.",
    "Tohle je přesně ten typ plánu, který končí explozí.",
    "Krytone, někdy bys mohl být méně dokonalý, víš?",
    "Neříkám, že je to špatný nápad… ale ano, je to špatný nápad.",
    "Jsem génius! Jen to zatím nikdo nepoznal.",
    "Tohle je tak špatné, že už to ani nemůže být horší… že?",
    "Rimmere, ty bys nedokázal zorganizovat ani vlastní snídani.",
    "Já nemám problém. Já mám spoustu menších katastrof.",
    "Kocoure, ty myslíš někdy i na něco jiného než na sebe?",
    "Tohle je přesně chvíle, kdy bych měl být někde úplně jinde.",
    "Já to zvládnu! …Dobře, nezvládnu, ale zkusím to.",
    "Rimmere, kdybys byl ještě o trochu víc neschopný, zmizíš.",
    "To není panika. To je jen velmi rychlé přemýšlení.",
    "Vesmír je nebezpečné místo. A já jsem v něm s vámi.",
    "Jmenuju se Rimmer. Arnold Rimmer. A jsem naprosto nepostradatelný.",
    "Krytone, tohle je rozkaz! Přestaň poslouchat rozkazy!",
    "To není moje chyba! Já jsem hlasoval proti!",
    "Já jsem hrdina! Jen jsem měl smůlu na okolnosti.",
    "Listere, ty jsi naprostý barbar!",
    "Tohle není zbabělost. To je strategický ústup.",
    "Kocoure, ty nemáš ani špetku sebekontroly.",
    "Já mám vždycky pravdu. Jen se to občas ukáže později.",
    "Tohle je naprosto bezpečné… myslím.",
    "Krytone, analyzuj situaci! – Situace: jsme v koncích, pane.",
    "Já se nevzdávám! Jen… měním plán.",
    "Tohle je typická ukázka totální neschopnosti.",
    "Listere, ty jsi největší prasák v celé galaxii.",
    "Já bych to zvládl lépe… kdybych to dělal já.",
    "Tohle není konec. To je jen velmi špatný začátek.",
    "Hej vy tam! Potřebujeme kuličky! Nejsme tady na vesmírném pikniku!",
    "Klikejte na tu obrazovku! Moje babička by klikala rychleji a to je už mrtvá!",
    "Ztrácíme energii! Pošlete okamžitě kuličky, nebo nás to vcucne do černé díry!",
    "Vesmírná anomálie? Ne, to je jen vaše lenost! Klikat, klikat, klikat!",
    "Potřebujeme energii na štíty! Posádko, do boje!"
  ],
  EN: [
    "Do you smoke? Only after sex. So not at all.",
    "I am completely reliable! It's just circumstances that are against me!",
    "That's not a disaster, that's a total smeg!",
    "Rimmer, you're such a dummy you'd lose your own shadow.",
    "Kryten, stop being so damn obedient!",
    "I'm the last human alive... and it just has to be me.",
    "This is a plan? More like a desperate attempt not to die.",
    "If something can go wrong, Rimmer will make it go wrong.",
    "This is the worst situation I've ever been in... and I was Rimmer's roommate.",
    "I'm not a coward! I just have a highly developed sense of self-preservation.",
    "Cat, you are completely useless. But I look great doing it.",
    "This is not a problem. It's an absolute disaster.",
    "Rimmer, you are walking proof that evolution can go backwards.",
    "I have a plan. And it's even better than no plan.",
    "We are lost in space, with no chance of return... anyone fancy a curry?",
    "I am so brilliant, it's almost unfair.",
    "Rimmer, you are completely useless... and slow to boot.",
    "This is exactly the type of plan that ends in an explosion.",
    "Kryten, you could be a little less perfect sometimes, you know?",
    "I'm not saying it's a bad idea... but yes, it's a bad idea.",
    "I'm a genius! Nobody has realized it yet, though.",
    "This is so bad it can't possibly get any worse... right?",
    "Rimmer, you couldn't even organize your own breakfast.",
    "I don't have a problem. I have a lot of minor disasters.",
    "Cat, do you ever think about anything other than yourself?",
    "This is exactly the moment I should be somewhere else entirely.",
    "I can handle this! ...Okay, I can't, but I'll try.",
    "Rimmer, if you were any more incompetent, you'd vanish.",
    "This isn't panic. It's just very fast thinking.",
    "Space is a dangerous place. And I'm in it with you.",
    "My name is Rimmer. Arnold Rimmer. And I am absolutely indispensable.",
    "Kryten, this is an order! Stop obeying orders!",
    "It's not my fault! I voted against it!",
    "I'm a hero! I just had bad luck with the circumstances.",
    "Lister, you are an absolute barbarian!",
    "This isn't cowardice. It's a strategic retreat.",
    "Cat, you have absolutely no self-control.",
    "I'm always right. It just sometimes takes a while to show.",
    "This is perfectly safe... I think.",
    "Kryten, analyze the situation! Situation: we are doomed, sir.",
    "I'm not giving up! I'm just... changing the plan.",
    "This is a prime example of total incompetence.",
    "Lister, you are the biggest slob in the entire galaxy.",
    "I could have done it better... if I was doing it.",
    "This is not the end. It's just a very bad beginning.",
    "Hey you out there! We need drops! We're not on a space picnic here!",
    "Tap that screen! My grandmother would tap faster and she's dead!",
    "We're losing energy! Send drops immediately or we'll get sucked into a black hole!",
    "Space anomaly? No, that's just your laziness! Tap, tap, tap!",
    "We need energy for shields! Crew, to your battle stations!"
  ]
};

