const T = {
  EN: {
    GRAV: "Gravity:", BOUNCE: "Bounce:", SPAWN: "Spawn Limit:", CHANCE: "Boss/Ship%:",
    SFX: "SFX Vol:", TTS_VOL: "Voice Vol:", RATE: "Mothership/s:", LIVE: "🔴 LIVE ",
    SYS_ON: "SYSTEM: ONLINE", SYNC: "GEOMETRY: PROCEDURAL | DATA: SYNCED",
    GFORCE: "G-FORCE:", BOUNCEX: "BOUNCE-X:", REC: "MISSION MILESTONES",
    WARP_CORE: "WARP CORE:", ACT_UNITS: "DROPPED UNITS:", TOT_UNITS: "TOTAL UNITS:",
    COOL: "COOLING DOWN...", TOP: "TOP CONTRIBUTORS", WARN: "WARNING: CLEANUP",
    RET: "REMAINING UNITS RETURNING TO BASE...", COMPL: "ROUND COMPLETE",
    SECTOR: "SECTOR:", NEXT: "NEXT ROUND IN:", LEVI: "VOID LEVIATHAN HP",
    SLAY: " BOSS SLAYER", NEW_C: "🔥 NEW COMMANDER! 🔥", L_PL: "LIVE_PLAYER",
    MARQ: "🚀 LIVE SECTOR: {0} --- ACTIVE UNITS: {1} --- SEND LIKES TO POWER UP Shields! --- ",
    TTS_INC: "Incoming vessel from ", TTS_POW: "Power up from ", TTS_MET: "Warning! Incoming meteor shower!",
    TTS_BH: "Warning! Black hole singularity forming!", TTS_COS: "Warning! Cosmic anomaly detected.",
    TTS_B_ENT: "VOID LEVIATHAN DETECTED. ENCOUNTER COMMENCING.", TTS_B_DEF: "Leviathan destroyed! Massive bonus awarded!",
    TTS_DEF: "Defense unit deployed.", TTS_10S: "10 seconds remaining.",
    TTS_SEC_C: "Sector operations complete.", TTS_SEC_W: "Welcome to sector ",
    TTS_R_O: "Round over! The ultimate commander is ", TTS_WELC: "Welcome commander ",
    TTS_RIMMER_ON: "Warning! Rimmer Mode Activated!", TTS_RIMMER_OFF: "Rimmer Mode Deactivated.", RIM_MODE: "RIMMER MODE",
    ANOMALY: "TEMPORAL ANOMALY", PHYS_ALT: "Physics altered!"
  },
  CZ: {
    GRAV: "Gravitace:", BOUNCE: "Odraz:", SPAWN: "Limit spawnu:", CHANCE: "Šance Boss/Loď%:",
    SFX: "Hlasitost SFX:", TTS_VOL: "Hlasitost robota:", RATE: "Mothership/s:", LIVE: "🔴 ŽIVĚ ",
    SYS_ON: "SYSTÉM: ONLINE", SYNC: "GEOMETRIE: PROCEDURÁLNÍ | DATA: SYNCHRO",
    GFORCE: "G-SÍLA:", BOUNCEX: "ODRAZ-X:", REC: "DNEŠNÍ REKORDY",
    WARP_CORE: "WARP JADRO:", ACT_UNITS: "SPADLÉ KULIČKY:", TOT_UNITS: "CELKEM KULIČEK:",
    COOL: "CHLAZENÍ...", TOP: "NEJLEPŠÍ HRÁČI", WARN: "VAROVÁNÍ: ÚKLID",
    RET: "ZBYLÉ JEDNOTKY SE VRACÍ NA ZÁKLADNU...", COMPL: "KOLO DOKONČENO",
    SECTOR: "SEKTOR:", NEXT: "DALŠÍ KOLO ZA:", LEVI: "ZDRAVÍ LEVIATHANA",
    SLAY: " ZABIJÁK BOSSE", NEW_C: "🔥 NOVÝ VELITEL! 🔥", L_PL: "ŽIVÝ_HRÁČ",
    MARQ: "🚀 ŽIVÝ SEKTOR: {0} --- AKTIVNÍ JEDNOTKY: {1} --- POŠLI LIKY PRO POSÍLENÍ ŠTÍTŮ! --- ",
    TTS_INC: "Přilétá loď od ", TTS_POW: "Vylepšení od ", TTS_MET: "Varování! Blíží se meteorický roj!",
    TTS_BH: "Varování! Formuje se singularita černé díry!", TTS_COS: "Varování! Detekována vesmírná anomálie.",
    TTS_B_ENT: "VOID LEVIATHAN DETEKOVÁN. ZAHÁJENÍ STŘETU.", TTS_B_DEF: "Leviathan zničen! Udělen obrovský bonus!",
    TTS_DEF: "Obranná jednotka nasazena.", TTS_10S: "Zbývá 10 sekund.",
    TTS_SEC_C: "Operace v sektoru dokončeny.", TTS_SEC_W: "Vítejte v sektoru ",
    TTS_R_O: "Kolo skončilo! Ultimátním velitelem je ", TTS_WELC: "Vítej veliteli ",
    TTS_RIMMER_ON: "Varování! Rimmer Mód Aktivován!", TTS_RIMMER_OFF: "Rimmer Mód Deaktivován.", RIM_MODE: "RIMMER MÓD",
    ANOMALY: "ČASOVÁ ANOMÁLIA", PHYS_ALT: "Fyzika zmenená!"
  }
};

const SPAM_MSGS = {
  CZ: [
    "{0} si pálí prst o displej!",
    "Pozor, {0} to tam sází jako o život!",
    "Velitel {0} má asi křeč v prstu!",
    "{0} žhaví obrazovku na maximum!",
    "Zastavte někdo hráče {0}, nebo nám praskne sklo!"
  ],
  EN: [
    "{0} is burning their finger on the screen!",
    "Watch out, {0} is tapping like crazy!",
    "Commander {0} must have a finger cramp!",
    "{0} is heating up the display to the max!",
    "Someone stop {0} before the glass breaks!"
  ]
};

const JOKES = {
  CZ: [
    "„Kouříš?“ – „Jen po sexu.“ – „Takže vůbec.“",
    "Jsem naprosto spolehlivý! To jen okolnosti jsou proti mně!",
    "To není katastrofa, to je totální smeg!",
    "Rimmere, ty jsi takový trouba, že bys ztratil i vlastní stín.",
    "Krytone, přestaň být tak zatraceně poslušný!",
    "Jsem poslední člověk naživu… a jsem to zrovna já.",
    "Tohle je plán? To je spíš zoufalý pokus neumřít.",
    "Když se něco může pokazit, Rimmer to pokazí.",
    "Tohle je nejhorší situace, v jaké jsem kdy byl… a to jsem byl Rimmerův spolubydlící.",
    "Já nejsem zbabělec! Jen mám vysoce vyvinutý pud sebezáchovy.",
    "Kocoure, ty jsi úplně k ničemu. – Ale vypadám u toho skvěle.",
    "To není problém. To je naprostá katastrofa.",
    "Rimmere, ty jsi chodící důkaz, že evoluce může jít i pozpátku.",
    "Já mám plán. A je dokonce lepší než žádný plán.",
    "Jsme ztraceni ve vesmíru, bez šance na návrat… dá si někdo curry?",
    "Já jsem tak skvělý, až je to skoro nespravedlivé.",
    "Rimmere, ty jsi úplně k ničemu… a ještě k tomu pomalý.",
    "Tohle je přesně ten typ plánu, který končí explozí.",
    "Krytone, někdy bys mohl být méně dokonalý, víš?",
    "Neříkám, že je to špatný nápad… ale ano, je to špatný nápad.",
    "Jsem génius! Jen to zatím nikdo nepoznal.",
    "Tohle je tak špatné, že už to ani nemůže být horší… že?",
    "Rimmere, ty bys nedokázal zorganizovat ani vlastní snídani.",
    "Já nemám problém. Já mám spoustu menších katastrof.",
    "Kocoure, ty myslíš někdy i na něco jiného než na sebe?",
    "Tohle je přesně chvíle, kdy bych měl být někde úplně jinde.",
    "Já to zvládnu! …Dobře, nezvládnu, ale zkusím to.",
    "Rimmere, kdybys byl ještě o trochu víc neschopný, zmizíš.",
    "To není panika. To je jen velmi rychlé přemýšlení.",
    "Vesmír je nebezpečné místo. A já jsem v něm s vámi.",
    "Jmenuju se Rimmer. Arnold Rimmer. A jsem naprosto nepostradatelný.",
    "Krytone, tohle je rozkaz! Přestaň poslouchat rozkazy!",
    "To není moje chyba! Já jsem hlasoval proti!",
    "Já jsem hrdina! Jen jsem měl smůlu na okolnosti.",
    "Listere, ty jsi naprostý barbar!",
    "Tohle není zbabělost. To je strategický ústup.",
    "Kocoure, ty nemáš ani špetku sebekontroly.",
    "Já mám vždycky pravdu. Jen se to občas ukáže později.",
    "Tohle je naprosto bezpečné… myslím.",
    "Krytone, analyzuj situaci! – Situace: jsme v koncích, pane.",
    "Já se nevzdávám! Jen… měním plán.",
    "Tohle je typická ukázka totální neschopnosti.",
    "Listere, ty jsi největší prasák v celé galaxii.",
    "Já bych to zvládl lépe… kdybych to dělal já.",
    "Tohle není konec. To je jen velmi špatný začátek.",
    "Hej vy tam! Potřebujeme kuličky! Nejsme tady na vesmírném pikniku!",
    "Klikejte na tu obrazovku! Moje babička by klikala rychleji a to je už mrtvá!",
    "Ztrácíme energii! Pošlete okamžitě kuličky, nebo nás to vcucne do černé díry!",
    "Vesmírná anomálie? Ne, to je jen vaše lenost! Klikat, klikat, klikat!",
    "Potřebujeme energii na štíty! Posádko, do boje!",
    "Všichni jsou mrtví, Dave.",
    "Peterson je mrtvý, Dave.",
    "Kochanská je mrtvá, Dave.",
    "A co kapitán Hollister?",
    "Všichni. Jsou. Mrtví. Dave.",
    "Polívka gazpacho! Kdybych věděl, že se podává studená...",
    "Uďte uzenáče, k snídani jsem zpátky.",
    "Křemíkové nebe neexistuje? A kam by potom přišly všechny ty kalkulačky?",
    "Dám si malou pauzu. Tak tři miliony let.",
    "Listere, tvůj zpěv je zbraň hromadného ničení.",
    "Jsem Arnold J. Rimmer. BDP. SDP.",
    "BDP znamená Bronzový diplom za plavání. Žádná sranda.",
    "Tohle je vzpoura, pane! Tedy, pokud s tím souhlasíte.",
    "Dejte si toust! Jsem toustovač a chci dělat tousty!",
    "A co takhle sýrový croissant?",
    "Nikdo nechce žádný smradlavý toust!",
    "Základní směrnice Vesmírného sboru 34124: Žádný důstojník s umělým chrupem by neměl zkoušet hrát na trumpetu.",
    "Mám pocit, že moje ego je to jediné, co drží tuhle loď pohromadě.",
    "Je to mimozemšťan! Ne, počkat, to je jen Listerovo spodní prádlo.",
    "Když se na tebe dívám, Rimmere, přeju si být zase vypnutý.",
    "Kocoure, tohle fakt není módní přehlídka!",
    "Zlato, všechno je módní přehlídka, když vypadáš jako já.",
    "Tohle je horší než hrát Scrabble s hologramem.",
    "Jsem naštvaný, unavený a chci svoje kuře vindaloo!",
    "Je to malý krok pro lidstvo, ale obrovský skok pro mou průměrnost.",
    "Holly, jaký je náš stav? - Jsme ztraceni, pane.",
    "Dovolte mi upozornit vás na fakt, že za 10 sekund explodujeme.",
    "Takže náš plán je nedělat nic a doufat, že to vybuchne někomu jinému?",
    "Jsem Toustovač! Moje jméno je Toustovač!",
    "Tohle je ta nejhorší a nejšpinavější loď v celé Jupiterské důlní společnosti.",
    "Základní směrnice Vesmírného sboru 1742: Žádný člen posádky nesmí na kapitána dělat opičky.",
    "Rimmere, ty jsi tak neschopný, že bys zkazil i vlastní zpopelnění.",
    "Krytone, co je to za tlačítko? - To je autodestrukce, pane. Nemačkejte ho.",
    "Zase jsme v háji. A tentokrát to opravdu nebyl můj nápad.",
    "Nouzový protokol zahájen: Všichni běhejte v kruzích a mávejte rukama.",
    "Když jsme u toho, kdo mi snědl moji poslední konzervu fazolí?",
    "Listere, ty jsi chodící biologická zbraň.",
    "Já nejsem plešatý, to je jen solární panel pro mou genialitu.",
    "A pak prý, že roboti nemají duši. My máme duši, jen je křemíková.",
    "Kocoure, jestli nepřestaneš zpívat, vyhodím tě z přechodové komory.",
    "Rimmere, i tvůj hologramní mozek je plný chyb.",
    "My jsme Červený trpaslík. My neutíkáme. My jen velmi rychle ustupujeme.",
    "Jaký je to pocit, být jediný živý tvor široko daleko a přesto být na dně potravního řetězce?",
    "Moje ponožky už vyhlásily nezávislost.",
    "Tohle není bordel, to je pečlivě organizovaný chaos.",
    "Může někdo vypnout toho zatraceného Toustovače?!",
    "Tohle je nefalšovaný, absolutní, stoprocentní průšvih.",
    "Holly, ukaž mi mapu! - Mapu nemám, ale můžu vám ukázat obrázek koně.",
    "Já se nezbláznil, já už takový byl!",
    "Tahle loď potřebuje víc kuliček a míň Rimmera!",
    "Stream padá! Naházejte tam další lajky, ať to udržíme!",
    "Víc odrazu! Víc gravitace! Víc všeho!",
    "Rimmere, kdybys byl kulička, ani bys nedopadl do chlívku.",
    "Potřebujeme štíty na maximum! Rychle, klikejte!",
    "Jestli nebudete lajkovat, pustím vám Listerovu hru na kytaru!",
    "Kuličky padají jako slzy mých nepřátel.",
    "Ještě jeden lajk a Kryton vám upeče palačinku.",
    "Kosmik je připraven! Ale chybí nám lajky do motoru!",
    "Pozor, blíží se meteorický roj! Schovejte si kari!"
  ],
  EN: [
    "Do you smoke? Only after sex. So not at all.",
    "I am completely reliable! It's just circumstances that are against me!",
    "That's not a disaster, that's a total smeg!",
    "Rimmer, you're such a dummy you'd lose your own shadow.",
    "Kryten, stop being so damn obedient!",
    "I'm the last human alive... and it just has to be me.",
    "This is a plan? More like a desperate attempt not to die.",
    "If something can go wrong, Rimmer will make it go wrong.",
    "This is the worst situation I've ever been in... and I was Rimmer's roommate.",
    "I'm not a coward! I just have a highly developed sense of self-preservation.",
    "Cat, you are completely useless. But I look great doing it.",
    "This is not a problem. It's an absolute disaster.",
    "Rimmer, you are walking proof that evolution can go backwards.",
    "I have a plan. And it's even better than no plan.",
    "We are lost in space, with no chance of return... anyone fancy a curry?",
    "I am so brilliant, it's almost unfair.",
    "Rimmer, you are completely useless... and slow to boot.",
    "This is exactly the type of plan that ends in an explosion.",
    "Kryten, you could be a little less perfect sometimes, you know?",
    "I'm not saying it's a bad idea... but yes, it's a bad idea.",
    "I'm a genius! Nobody has realized it yet, though.",
    "This is so bad it can't possibly get any worse... right?",
    "Rimmer, you couldn't even organize your own breakfast.",
    "I don't have a problem. I have a lot of minor disasters.",
    "Cat, do you ever think about anything other than yourself?",
    "This is exactly the moment I should be somewhere else entirely.",
    "I can handle this! ...Okay, I can't, but I'll try.",
    "Rimmer, if you were any more incompetent, you'd vanish.",
    "This isn't panic. It's just very fast thinking.",
    "Space is a dangerous place. And I'm in it with you.",
    "My name is Rimmer. Arnold Rimmer. And I am absolutely indispensable.",
    "Kryten, this is an order! Stop obeying orders!",
    "It's not my fault! I voted against it!",
    "I'm a hero! I just had bad luck with the circumstances.",
    "Lister, you are an absolute barbarian!",
    "This isn't cowardice. It's a strategic retreat.",
    "Cat, you have absolutely no self-control.",
    "I'm always right. It just sometimes takes a while to show.",
    "This is perfectly safe... I think.",
    "Kryten, analyze the situation! Situation: we are doomed, sir.",
    "I'm not giving up! I'm just... changing the plan.",
    "This is a prime example of total incompetence.",
    "Lister, you are the biggest slob in the entire galaxy.",
    "I could have done it better... if I was doing it.",
    "This is not the end. It's just a very bad beginning.",
    "Hey you out there! We need drops! We're not on a space picnic here!",
    "Tap that screen! My grandmother would tap faster and she's dead!",
    "We're losing energy! Send drops immediately or we'll get sucked into a black hole!",
    "Space anomaly? No, that's just your laziness! Tap, tap, tap!",
    "We need energy for shields! Crew, to your battle stations!",
    "Everybody's dead, Dave.",
    "Peterson isn't, is he? Everybody is dead, Dave.",
    "Kochanski is dead, Dave.",
    "What about Captain Hollister?",
    "Everybody. Is. Dead. Dave.",
    "Gazpacho soup! If only I'd known it was served cold...",
    "Smoke me a kipper, I'll be back for breakfast.",
    "No Silicon Heaven? Where would all the calculators go?",
    "I'll just take a little break. For about three million years.",
    "Lister, your singing is a weapon of mass destruction.",
    "I am Arnold J. Rimmer. BSc. SSc.",
    "BSc stands for Bronze Swimming certificate. Not a joke.",
    "This is a mutiny, sir! That is, if you agree with it.",
    "Would anyone like any toast? I am a toaster and I toast!",
    "How about a cheese croissant?",
    "Nobody wants any smegging toast!",
    "Space Corps Directive 34124: No officer with false teeth should attempt oral sex in zero gravity.",
    "I feel like my ego is the only thing keeping this ship together.",
    "It's an alien! No, wait, it's just Lister's underpants.",
    "Looking at you, Rimmer, makes me wish I was switched off again.",
    "Cat, this is really not a fashion show!",
    "Honey, everything is a fashion show when you look like me.",
    "This is worse than playing Scrabble with a hologram.",
    "I'm angry, I'm tired, and I want my chicken vindaloo!",
    "It's one small step for mankind, but a giant leap for my mediocrity.",
    "Holly, what's our status? - We are lost, sir.",
    "Allow me to point out that we are going to explode in 10 seconds.",
    "So our plan is to do nothing and hope it blows up someone else?",
    "I am the Toaster! My name is Toaster!",
    "This is the worst, filthiest ship in the entire Jupiter Mining Corporation.",
    "Space Corps Directive 1742: No member of the crew should report for active duty wearing a ginger toupee.",
    "Rimmer, you are so incompetent you'd botch your own cremation.",
    "Kryten, what is this button? - That is self-destruct, sir. Please don't press it.",
    "We are screwed again. And this time it wasn't even my fault.",
    "Emergency protocol initiated: Everyone run in circles and wave your arms.",
    "Speaking of which, who ate my last can of baked beans?",
    "Lister, you are a walking biological weapon.",
    "I am not bald, it's just a solar panel for my genius.",
    "And they say robots have no soul. We have a soul, it's just silicon.",
    "Cat, if you don't stop singing, I will throw you out the airlock.",
    "Rimmer, even your holographic brain is full of bugs.",
    "We are Red Dwarf. We don't run. We just retreat very quickly.",
    "How does it feel to be the only living creature for lightyears and still be at the bottom of the food chain?",
    "My socks have already declared independence.",
    "This is not a mess, this is carefully organized chaos.",
    "Can somebody please turn off that smegging Toaster?!",
    "This is an unadulterated, absolute, one hundred percent disaster.",
    "Holly, show me the map! - I don't have a map, but I can show you a picture of a horse.",
    "I haven't gone crazy, I was always like this!",
    "This ship needs more balls and less Rimmer!",
    "Stream is crashing! Throw in more likes so we can hold it together!",
    "More bounce! More gravity! More everything!",
    "Rimmer, if you were a drop, you wouldn't even land in the bucket.",
    "We need shields at maximum! Quick, click!",
    "If you don't like, I will play Lister's guitar track!",
    "The balls are falling like the tears of my enemies.",
    "One more like and Kryten will bake you a pancake.",
    "Starbug is ready! But we are missing likes for the engine!",
    "Warning, meteor shower approaching! Hide your curry!"
  ]
};
