const T = {
  EN: {
    GRAV: "Gravity:", BOUNCE: "Bounce:", SPAWN: "Spawn Limit:", CHANCE: "Boss/Ship%:",
    SFX: "SFX Vol:", TTS_VOL: "Voice Vol:", RATE: "Mothership/s:", LIVE: "🔴 LIVE ",
    SYS_ON: "SYSTEM: ONLINE", SYNC: "GEOMETRY: PROCEDURAL | DATA: SYNCED",
    GFORCE: "G-FORCE:", BOUNCEX: "BOUNCE-X:", REC: "MISSION MILESTONES",
    WARP_CORE: "WARP CORE:", ACT_UNITS: "DROPPED UNITS:", TOT_UNITS: "TOTAL UNITS:",
    COOL: "COOLING DOWN...", TOP: "TOP CONTRIBUTORS", WARN: "WARNING: CLEANUP",
    RET: "REMAINING UNITS RETURNING TO BASE...", COMPL: "ROUND COMPLETE",
    SECTOR: "SECTOR:", NEXT: "NEXT ROUND IN:", LEVI: "VOID LEVIATHAN HP",
    SLAY: " BOSS SLAYER", NEW_C: "🔥 NEW COMMANDER! 🔥", L_PL: "LIVE_PLAYER",
    MARQ: "🚀 LIVE SECTOR: {0} --- ACTIVE UNITS: {1} --- SEND LIKES TO POWER UP Shields! --- ",
    TTS_INC: "Incoming vessel from ", TTS_POW: "Power up from ", TTS_MET: "Warning! Incoming meteor shower!",
    TTS_BH: "Warning! Black hole singularity forming!", TTS_COS: "Warning! Cosmic anomaly detected.",
    TTS_B_ENT: "VOID LEVIATHAN DETECTED. ENCOUNTER COMMENCING.", TTS_B_DEF: "Leviathan destroyed! Massive bonus awarded!",
    TTS_DEF: "Defense unit deployed.", TTS_10S: "10 seconds remaining.",
    TTS_SEC_C: "Sector operations complete.", TTS_SEC_W: "Welcome to sector ",
    TTS_R_O: "Round over! The ultimate commander is ", TTS_WELC: "Welcome commander ",
    TTS_RIMMER_ON: "Warning! Rimmer Mode Activated!", TTS_RIMMER_OFF: "Rimmer Mode Deactivated.", RIM_MODE: "RIMMER MODE",
    ANOMALY: "TEMPORAL ANOMALY", PHYS_ALT: "Physics altered!"
  },
  CZ: {
    GRAV: "Gravitace:", BOUNCE: "Odraz:", SPAWN: "Limit spawnu:", CHANCE: "Šance Boss/Loď%:",
    SFX: "Hlasitost SFX:", TTS_VOL: "Hlasitost robota:", RATE: "Mothership/s:", LIVE: "🔴 ŽIVĚ ",
    SYS_ON: "SYSTÉM: ONLINE", SYNC: "GEOMETRIE: PROCEDURÁLNÍ | DATA: SYNCHRO",
    GFORCE: "G-SÍLA:", BOUNCEX: "ODRAZ-X:", REC: "DNEŠNÍ REKORDY",
    WARP_CORE: "WARP JÁDRO:", ACT_UNITS: "SPADLÉ KULIČKY:", TOT_UNITS: "CELKEM KULIČEK:",
    COOL: "CHLAZENÍ...", TOP: "NEJLEPŠÍ HRÁČI", WARN: "VAROVÁNÍ: ÚKLID",
    RET: "ZBYLÉ JEDNOTKY SE VRACÍ NA ZÁKLADNU...", COMPL: "KOLO DOKONČENO",
    SECTOR: "SEKTOR:", NEXT: "DALŠÍ KOLO ZA:", LEVI: "ZDRAVÍ LEVIATHANA",
    SLAY: " ZABIJÁK BOSSE", NEW_C: "🔥 NOVÝ VELITEL! 🔥", L_PL: "ŽIVÝ_HRÁČ",
    MARQ: "🚀 ŽIVÝ SEKTOR: {0} --- AKTIVNÍ JEDNOTKY: {1} --- POŠLI LIKY PRO POSÍLENÍ ŠTÍTŮ! --- ",
    TTS_INC: "Přilétá loď od ", TTS_POW: "Vylepšení od ", TTS_MET: "Varování! Blíží se meteorický roj!",
    TTS_BH: "Varování! Formuje se singularita černé díry!", TTS_COS: "Varování! Detekována vesmírná anomálie.",
    TTS_B_ENT: "VOID LEVIATHAN DETEKOVÁN. ZAHÁJENÍ STŘETU.", TTS_B_DEF: "Leviathan zničen! Udělen obrovský bonus!",
    TTS_DEF: "Obranná jednotka nasazena.", TTS_10S: "Zbývá 10 sekund.",
    TTS_SEC_C: "Operace v sektoru dokončeny.", TTS_SEC_W: "Vítejte v sektoru ",
    TTS_R_O: "Kolo skončilo! Ultimátním velitelem je ", TTS_WELC: "Vítej veliteli ",
    TTS_RIMMER_ON: "Varování! Rimmer Mód Aktivován!", TTS_RIMMER_OFF: "Rimmer Mód Deaktivován.", RIM_MODE: "RIMMER MÓD",
    ANOMALY: "ČASOVÁ ANOMÁLIE", PHYS_ALT: "Fyzika změněna!"
  }
};

const SPAM_MSGS = {
  CZ: [
    "{0} si pálí prst o displej!",
    "Pozor, {0} to tam sází jako o život!",
    "Velitel {0} má asi křeč v prstu!",
    "{0} žhaví obrazovku na maximum!",
    "Zastavte někdo hráče {0}, nebo nám praskne sklo!"
  ],
  EN: [
    "{0} is burning their finger on the screen!",
    "Watch out, {0} is tapping like crazy!",
    "Commander {0} must have a finger cramp!",
    "{0} is heating up the display to the max!",
    "Someone stop {0} before the glass breaks!"
  ]
};

const JOKES = {
  CZ: [
    "Všichni jsou mrtví, Dave.",
    "Peterson je mrtvý, Dave.",
    "Kochanská je mrtvá, Dave.",
    "A co kapitán Hollister?",
    "Všichni. Jsou. Mrtví. Dave.",
    "Polívka gazpacho! Kdybych věděl, že se podává studená...",
    "Uďte uzenáče, k snídani jsem zpátky.",
    "Křemíkové nebe neexistuje? A kam by potom přišly všechny ty kalkulačky?",
    "„Kouříš?“ – „Jen po sexu.“ – „Takže vůbec.“",
    "Jsem naprosto spolehlivý! To jen okolnosti jsou proti mně!",
    "To není katastrofa, to je totální smeg!",
    "Rimmere, ty jsi takový trouba, že bys ztratil i vlastní stín.",
    "Krytone, přestaň být tak zatraceně poslušný!",
    "Jsem poslední člověk naživu… a jsem to zrovna já.",
    "Tohle je plán? To je spíš zoufalý pokus neumřít.",
    "Když se něco může pokazit, Rimmer to pokazí.",
    "Tohle je nejhorší situace, v jaké jsem kdy byl… a to jsem byl Rimmerův spolubydlící.",
    "Já nejsem zbabělec! Jen mám vysoce vyvinutý pud sebezáchovy.",
    "Kocoure, ty jsi úplně k ničemu. – Ale vypadám u toho skvěle.",
    "To není problém. To je naprostá katastrofa.",
    "Rimmere, ty jsi chodící důkaz, že evoluce může jít i pozpátku.",
    "Já mám plán. A je dokonce lepší než žádný plán.",
    "Jsme ztraceni ve vesmíru, bez šance na návrat… dá si někdo curry?",
    "Já jsem tak skvělý, až je to skoro nespravedlivé.",
    "Rimmere, ty jsi úplně k ničemu… a ještě k tomu pomalý.",
    "Tohle je přesně ten typ plánu, který končí explozí.",
    "Krytone, někdy bys mohl být méně dokonalý, víš?",
    "Neříkám, že je to špatný nápad… ale ano, je to špatný nápad.",
    "Jsem génius! Jen to zatím nikdo nepoznal.",
    "Tohle je tak špatné, že už to ani nemůže být horší… že?",
    "Rimmere, ty bys nedokázal zorganizovat ani vlastní snídani.",
    "Já nemám problém. Já mám spoustu menších katastrof.",
    "Kocoure, ty myslíš někdy i na něco jiného než na sebe?",
    "Tohle je přesně chvíle, kdy bych měl být někde úplně jinde.",
    "Já to zvládnu! …Dobře, nezvládnu, ale zkusím to.",
    "Rimmere, kdybys byl ještě o trochu víc neschopný, zmizíš.",
    "To není panika. To je jen velmi rychlé přemýšlení.",
    "Vesmír je nebezpečné místo. A já jsem v něm s vámi.",
    "Jmenuju se Rimmer. Arnold Rimmer. A jsem naprosto nepostradatelný.",
    "Krytone, tohle je rozkaz! Přestaň poslouchat rozkazy!",
    "To není moje chyba! Já jsem hlasoval proti!",
    "Já jsem hrdina! Jen jsem měl smůlu na okolnosti.",
    "Listere, ty jsi naprostý barbar!",
    "Tohle není zbabělost. To je strategický ústup.",
    "Kocoure, ty nemáš ani špetku sebekontroly.",
    "Já mám vždycky pravdu. Jen se to občas ukáže později.",
    "Tohle je naprosto bezpečné… myslím.",
    "Krytone, analyzuj situaci! – Situace: jsme v koncích, pane.",
    "Já se nevzdávám! Jen… měním plán.",
    "Tohle je typická ukázka totální neschopnosti.",
    "Listere, ty jsi největší prasák v celé galaxii.",
    "Já bych to zvládl lépe… kdybych to dělal já.",
    "Tohle není konec. To je jen velmi špatný začátek.",
    "Smeg.",
    "Vypadá to jako něco, co zbylo po výbuchu v továrně na lepidlo.",
    "Dáme si toast?",
    "Nechci žádný smradlavý toast!",
    "A co takhle vafli?",
    "Jsi tak tupý, že by sis uřízl ruku o lžíci.",
    "Jaká je šance? Asi jako najít pannu v bordelu.",
    "Pravidlo vesmírného sboru 196156: Kdokoli, kdo zachrání lodní majetek, má právo na pivo.",
    "My nikoho nezachraňujeme, my utíkáme.",
    "Měl jsem krásný sen. Všichni jste v něm zemřeli.",
    "Listere, jsi odporný. Je to vědecký fakt.",
    "To byl můj nejlepší oblek!",
    "Moje IQ má stejnou hodnotu jako počet učitelů tělocviku v galaxii.",
    "Krytone, já chci své slipy.",
    "Tohle se mi nelíbí. A když se mi něco nelíbí, obvykle to vybuchne.",
    "Tenhle dopis je od Výboru pro odškodnění.",
    "Dneska je ryba. Pstruh a la creme.",
    "Zemřeme. Všichni zemřeme.",
    "Bílá díra? Takže z ní vychází čas?",
    "Co to je? Bílá díra!",
    "Dám si na to trochu pálivé omáčky.",
    "Máš mozek z bramborové kaše.",
    "A co mimozemšťani? Třeba jsou to mimozemšťani!",
    "Změňte žárovku na červenou!",
    "Ty jsi muž bez špetky cti.",
    "Proč mě všichni tak nenávidí?",
    "To jsi celý ty, Rimmere.",
    "A co takhle malý kompromis: já přežiju a vy ne.",
    "Je to horší než špatné. Je to katastrofální.",
    "Kdo uvařil to kari? Dá se s tím řezat kov.",
    "Tři miliony let... to je zatraceně dlouhá doba.",
    "Moje noha má větší mozek než ty.",
    "Nechci tě znervózňovat, ale jsme naprosto v háji.",
    "Listere, proč je v mém lůžku kari?",
    "Protože v lednici už nebylo místo.",
    "Já jsem Holly, lodní počítač s IQ 6000.",
    "Zavři klapačku, Holly!",
    "Hej vy tam! Potřebujeme kuličky! Nejsme tady na vesmírném pikniku!",
    "Klikejte na tu obrazovku! Moje babička by klikala rychleji a to je už mrtvá!",
    "Ztrácíme energii! Pošlete okamžitě kuličky, nebo nás to vcucne do černé díry!",
    "Vesmírná anomálie? Ne, to je jen vaše lenost! Klikat, klikat, klikat!",
    "Potřebujeme energii na štíty! Posádko, do boje!",
    "Nepanikařte! Já panikařím za nás za všechny!",
    "Slyšíte tu hudbu? To je ticho z prázdných chlívků!",
    "Klikat! Víc kuliček rovná se víc naděje pro lidstvo!",
    "Kdo nekliká, jako by nežil. Dave, klikej!",
    "Můj účes právě ztratil tvar z nedostatku kuliček na obrazovce!",
    "Rimmere, i tahle obrazovka má víc charizmatu než ty.",
    "Štíty na 20 procent! Přidat kuličky, vy smegheadi!",
    "Krytone, co dělají naši diváci? Nudí se!",
    "Jestli nepošlete kuličku, začnu zpívat. A vy víte, co to znamená.",
    "Lajky, lidi, lajky! To je palivo budoucnosti!",
    "Pamatujte na pravidlo sboru: pokud něco bliká, klikejte na to!"
  ],
  EN: [
    "Everybody's dead, Dave.",
    "Peterson isn't, is he? Everybody is dead, Dave.",
    "Kochanski is dead, Dave.",
    "What about Captain Hollister?",
    "Everybody. Is. Dead. Dave.",
    "Gazpacho soup! If only I'd known it was served cold...",
    "Smoke me a kipper, I'll be back for breakfast.",
    "No Silicon Heaven? Where would all the calculators go?",
    "Do you smoke? Only after sex. So not at all.",
    "I am completely reliable! It's just circumstances that are against me!",
    "That's not a disaster, that's a total smeg!",
    "Rimmer, you're such a dummy you'd lose your own shadow.",
    "Kryten, stop being so damn obedient!",
    "I'm the last human alive... and it just has to be me.",
    "This is a plan? More like a desperate attempt not to die.",
    "If something can go wrong, Rimmer will make it go wrong.",
    "This is the worst situation I've ever been in... and I was Rimmer's roommate.",
    "I'm not a coward! I just have a highly developed sense of self-preservation.",
    "Cat, you are completely useless. But I look great doing it.",
    "This is not a problem. It's an absolute disaster.",
    "Rimmer, you are walking proof that evolution can go backwards.",
    "I have a plan. And it's even better than no plan.",
    "We are lost in space, with no chance of return... anyone fancy a curry?",
    "I am so brilliant, it's almost unfair.",
    "Rimmer, you are completely useless... and slow to boot.",
    "This is exactly the type of plan that ends in an explosion.",
    "Kryten, you could be a little less perfect sometimes, you know?",
    "I'm not saying it's a bad idea... but yes, it's a bad idea.",
    "I'm a genius! Nobody has realized it yet, though.",
    "This is so bad it can't possibly get any worse... right?",
    "Rimmer, you couldn't even organize your own breakfast.",
    "I don't have a problem. I have a lot of minor disasters.",
    "Cat, do you ever think about anything other than yourself?",
    "This is exactly the moment I should be somewhere else entirely.",
    "I can handle this! ...Okay, I can't, but I'll try.",
    "Rimmer, if you were any more incompetent, you'd vanish.",
    "This isn't panic. It's just very fast thinking.",
    "Space is a dangerous place. And I'm in it with you.",
    "My name is Rimmer. Arnold Rimmer. And I am absolutely indispensable.",
    "Kryten, this is an order! Stop obeying orders!",
    "It's not my fault! I voted against it!",
    "I'm a hero! I just had bad luck with the circumstances.",
    "Lister, you are an absolute barbarian!",
    "This isn't cowardice. It's a strategic retreat.",
    "Cat, you have absolutely no self-control.",
    "I'm always right. It just sometimes takes a while to show.",
    "This is perfectly safe... I think.",
    "Kryten, analyze the situation! Situation: we are doomed, sir.",
    "I'm not giving up! I'm just... changing the plan.",
    "This is a prime example of total incompetence.",
    "Lister, you are the biggest slob in the entire galaxy.",
    "I could have done it better... if I was doing it.",
    "This is not the end. It's just a very bad beginning.",
    "Smeg.",
    "It looks like something left over from an explosion in a glue factory.",
    "Would anyone like any toast?",
    "I don't want any smegging toast!",
    "How about a waffle?",
    "You're so thick, you'd cut your hand on a spoon.",
    "What are the chances? About the same as finding a virgin in a brothel.",
    "Space Corps Directive 196156: Any officer caught sniffing the saddle of the exercise bicycle...",
    "We are not rescuing anyone, we are fleeing.",
    "I had a beautiful dream. You all died.",
    "Lister, you are repulsive. It's a scientific fact.",
    "That was my best suit!",
    "My IQ has the same value as the number of PE teachers in the galaxy.",
    "Kryten, I want my underpants.",
    "I don't like this. And when I don't like something, it usually blows up.",
    "This letter is from the Committee for Compensation...",
    "Today's fish is Trout a la Creme.",
    "We are going to die. We are all going to die.",
    "A white hole? So time comes out of it?",
    "What is it? A white hole!",
    "I'll just put some hot sauce on it.",
    "You have a brain made of mashed potatoes.",
    "What about aliens? Maybe it's aliens!",
    "Change the bulb to red!",
    "You are a man without a shred of honor.",
    "Why does everybody hate me so much?",
    "That is so you, Rimmer.",
    "How about a little compromise: I live and you don't.",
    "It is worse than bad. It is disastrous.",
    "Who cooked this curry? You could cut metal with it.",
    "Three million years... that is a smegging long time.",
    "My foot has a bigger brain than you.",
    "I don't mean to alarm you, but we are totally smegged.",
    "Lister, why is there a curry in my bed?",
    "Because there was no room in the fridge.",
    "I am Holly, the ship's computer with an IQ of 6000.",
    "Shut your trap, Holly!",
    "Hey you out there! We need drops! We're not on a space picnic here!",
    "Tap that screen! My grandmother would tap faster and she's dead!",
    "We're losing energy! Send drops immediately or we'll get sucked into a black hole!",
    "Space anomaly? No, that's just your laziness! Tap, tap, tap!",
    "We need energy for shields! Crew, to your battle stations!",
    "Don't panic! I'm panicking for all of us!",
    "Do you hear that music? That's the silence of empty zones!",
    "Click! More balls equals more hope for humanity!",
    "He who does not click, is not truly alive. Dave, click!",
    "My hair just lost its shape due to a lack of balls on the screen!",
    "Rimmer, even this screen has more charisma than you.",
    "Shields at 20 percent! Add balls, you smegheads!",
    "Kryten, what are our viewers doing? Getting bored!",
    "If you don't drop a ball, I'll start singing. And you know what that means.",
    "Likes, people, likes! It's the fuel of the future!",
    "Remember the Corps directive: if it flashes, click it!"
  ]
};
